version: "3.8"
services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=rss
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: rss_db

  redis:
    image: redis:6
    ports:
      - 6379:6379
    container_name: rss_redis

  backend:
    build: .
    ports:
      - 8000:8000
    env_file:
      - rss_reader/.env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    container_name: rss_backend
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    command: celery -A rss_reader worker -l info
    container_name: rss_celery
    volumes:
      - .:/app
    env_file:
      - rss_reader/.env
    depends_on:
      - db
      - redis
      - backend

  celery-beat:
    build: .
    command: celery -A rss_reader beat -l info
    container_name: rss_celery_beat
    volumes:
      - .:/app
    env_file:
      - rss_reader/.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
